export LD_LIBRARY_PATH=${LD_LIBRARY_PATH/${CONDA_LIB}:/}
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH/${CUDNN_LIB}:/}
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH/${TENSORRT_PATH}:/}

unset CONDA_LIB
unset CUDNN_LIB
unset CUDNN_PATH
unset TENSORRT_PATH

unset OMPI_MCA_opal_cuda_support
unset XLA_FLAGS

unset TF_GPU_THREAD_MODE
unset TF_GPU_THREAD_COUNT
